eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9990/eureka
spring:
  application:
    name: order
# 服务名称
PRODUCT:
  ribbon:
    # 配置规则类的全限定名
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
