spring:
  application:
    name: order
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    port: 5672
    virtual-host: /
    # 开启发送确认
    publisher-confirms: true
    # 开启发送失败退回
    publisher-returns: true
    # 开启ACK
    listener:
      direct: 
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual

server:
  port: 9992
# 服务名称
PRODUCT:
  ribbon:
    # 配置规则类的全限定名
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
env:
  test15
